[versions]
kotlin = "2.1.20"
ktor = "3.1.3"
logback = "1.5.18"
hikari = "5.1.0"
postgresql = "42.7.4"
bcrypt = "0.10.2"
junit = "5.11.3"
testcontainers = "1.20.4"

[libraries]
ktor-server-core         = { module = "io.ktor:ktor-server-core-jvm",                   version.ref = "ktor" }
ktor-server-netty        = { module = "io.ktor:ktor-server-netty-jvm",                  version.ref = "ktor" }
ktor-server-auth         = { module = "io.ktor:ktor-server-auth-jvm",                   version.ref = "ktor" }
ktor-server-auth-jwt     = { module = "io.ktor:ktor-server-auth-jwt-jvm",               version.ref = "ktor" }
ktor-server-content-neg  = { module = "io.ktor:ktor-server-content-negotiation-jvm",    version.ref = "ktor" }
ktor-serialization-json  = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm",    version.ref = "ktor" }
logback                  = { module = "ch.qos.logback:logback-classic",                 version.ref = "logback" }
hikari                   = { module = "com.zaxxer:HikariCP",                            version.ref = "hikari" }
postgresql               = { module = "org.postgresql:postgresql",                      version.ref = "postgresql" }
bcrypt                   = { module = "at.favre.lib:bcrypt",                            version.ref = "bcrypt" }

ktor-server-test-host    = { module = "io.ktor:ktor-server-test-host-jvm",             version.ref = "ktor" }
junit-jupiter            = { module = "org.junit.jupiter:junit-jupiter",                version.ref = "junit" }
testcontainers-core      = { module = "org.testcontainers:testcontainers",              version.ref = "testcontainers" }
testcontainers-junit     = { module = "org.testcontainers:junit-jupiter",               version.ref = "testcontainers" }
testcontainers-pg        = { module = "org.testcontainers:postgresql",                  version.ref = "testcontainers" }
junit-platform-launcher  = { module = "org.junit.platform:junit-platform-launcher",       version = "1.11.3" }

[plugins]
kotlin-jvm              = { id = "org.jetbrains.kotlin.jvm",                  version.ref = "kotlin" }
kotlin-serialization    = { id = "org.jetbrains.kotlin.plugin.serialization",  version.ref = "kotlin" }
ktor                    = { id = "io.ktor.plugin",                             version.ref = "ktor" }
